version: '3.9'

services:
  database:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432"

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  blackfire:
    image: blackfire/blackfire
    env_file: .env.local
    ports: [8707]

  redis:
    image: redis:5-alpine
    ports: [6379]

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]