version: '3.9'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-main}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-main}
      POSTGRES_USER: ${POSTGRES_USER:-main}
    restart: always
    volumes:
      #- db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
