cat <<EOF | ssh $DEPLOYER_USERNAME@$PRODUCTION_SERVER_IP
cd $PRODUCTION_SERVER_PATH
export APP_MAINTENANCE=$APP_MAINTENANCE
export APP_SECRET=$APP_SECRET
export APP_URL=$APP_URL
export POSTGRES_USER=$POSTGRES_USER
export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
export POSTGRES_DB=$POSTGRES_DB
export SLACK_DSN=$SLACK_DSN
./deploy.sh
EOF